# Generated by Django 4.1.3 on 2023-01-27 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preferences', '0002_custom_populate_mealsetting'),
        ('shopping', '0001_initial'),
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_cooked', models.BooleanField(default=False)),
                ('portions_cooked', models.IntegerField(null=True)),
                ('is_eaten', models.BooleanField(default=False)),
                ('meal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preferences.mealsetting')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
                ('shopping_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping.shoppinglist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('date', 'meal', 'recipe', 'is_cooked', 'is_eaten')},
            },
        ),
    ]
