# Generated by Django 4.1.3 on 2023-01-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_cooked', models.BooleanField(default=False)),
                ('portions_cooked', models.IntegerField(null=True)),
                ('is_eaten', models.BooleanField(default=False)),
            ],
        ),
    ]
