# Generated by Django 4.1.3 on 2022-12-08 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0002_populate_meal_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('preferences', '0002_populate_meal_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_cooked', models.BooleanField(default=False)),
                ('portions_cooked', models.IntegerField()),
                ('is_eaten', models.BooleanField()),
                ('meals', models.ManyToManyField(related_name='days', to='preferences.mealsetting')),
                ('recipes', models.ManyToManyField(related_name='days', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
