# Generated by Django 4.1.3 on 2023-01-24 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplan',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preferences.mealsetting'),
        ),
    ]
