# Generated by Django 4.1.3 on 2022-12-11 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_populate_meal_tags'),
        ('preferences', '0002_populate_meal_settings'),
        ('plans', '0002_alter_dayplan_portions_cooked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayplan',
            name='meals',
        ),
        migrations.RemoveField(
            model_name='dayplan',
            name='recipes',
        ),
        migrations.AddField(
            model_name='dayplan',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='preferences.mealsetting'),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
    ]
