# Generated by Django 4.1.3 on 2022-12-12 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_populate_meal_tags'),
        ('preferences', '0002_populate_meal_settings'),
        ('plans', '0003_remove_dayplan_meals_remove_dayplan_recipes_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dayplan',
            unique_together={('date', 'meal', 'recipe')},
        ),
    ]
