# Generated by Django 4.1.3 on 2022-12-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_populate_meal_settings'),
        ('recipes', '0003_alter_recipe_name'),
        ('plans', '0004_alter_dayplan_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dayplan',
            unique_together={('date', 'meal', 'recipe', 'is_cooked', 'is_eaten')},
        ),
    ]
