# Generated by Django 4.1.3 on 2022-12-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_alter_dayplan_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayplan',
            name='portions_cooked',
            field=models.IntegerField(null=True),
        ),
    ]
