# Generated by Django 4.1.3 on 2022-12-13 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_remove_shoppinglist_cooked_recipes'),
        ('plans', '0006_alter_dayplan_portions_cooked'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplan',
            name='shopping_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping.shoppinglist'),
        ),
    ]
