# Generated by Django 4.1.3 on 2022-12-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_dayplan_shopping_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayplan',
            name='is_eaten',
            field=models.BooleanField(default=False),
        ),
    ]
