# Generated by Django 4.1.3 on 2023-01-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(choices=[(1, 'śniadanie'), (2, '2. śniadanie'), (3, 'przekąska'), (4, 'lunch'), (5, 'obiad'), (6, 'deser'), (7, 'podwieczorek'), (8, 'obiadokolacja'), (9, 'kolacja')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meals', models.ManyToManyField(to='preferences.mealsetting')),
            ],
        ),
    ]
