# Generated by Django 4.1.3 on 2023-01-25 22:18

from django.db import migrations

from preferences.models import MealSetting


def populate_meal_setting(apps, schema_editor):
    meals = ['śniadanie', '2. śniadanie', 'przekąska', 'lunch', 'obiad', 'deser', 'podwieczorek', 'obiadokolacja', 'kolacja']
    for meal in meals:
        MealSetting.objects.create(meal_name=meal)

def clean_meal_setting(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_meal_setting, clean_meal_setting)
    ]
