# Generated by Django 4.1.3 on 2022-12-08 14:32

from django.db import migrations, models

from preferences.models import MealSetting


def populate_meals(apps, schema_editor):

    meals = ['śniadanie', '2. śniadanie', 'przekąska', 'lunch', 'obiad', 'podwieczorek', 'obiadokolacja', 'kolacja']
    for meal in meals:
        MealSetting.objects.create(meal_name=meal)


def clean_meals(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_meals, clean_meals)
    ]