# Generated by Django 4.1.3 on 2023-01-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealsetting',
            name='meal_name',
            field=models.CharField(max_length=30),
        ),
    ]
