# Generated by Django 4.1.3 on 2022-12-07 08:43

from django.db import migrations, models

from recipes.models import MealTag


def populate_meal_tag(apps, schema_editor):

    meal_tags = ['śniadanie', 'przekąska', 'obiad', 'kolacja', 'zupa', 'na drogę']
    for tag in meal_tags:
        MealTag.objects.create(meal_tag=tag)


def clean_meal_tag(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_meal_tag, clean_meal_tag)
    ]
