# Generated by Django 4.1.3 on 2022-12-06 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='products',
            new_name='ingredients',
        ),
    ]
