# Generated by Django 4.1.3 on 2022-12-13 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_alter_dayplan_portions_cooked'),
        ('shopping', '0002_rename_shoppinglists_shoppinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='cooked_recipes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.dayplan'),
        ),
    ]
