# Generated by Django 4.1.3 on 2022-12-13 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_alter_shoppinglist_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='cooked_recipes',
        ),
    ]
